//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int ID { get; set; }
        public string Acontent { get; set; }
        public string Aurl { get; set; }
        public System.DateTime Atime { get; set; }
        public bool Arange { get; set; }
        public string Aadress { get; set; }
        public bool AIsdelete { get; set; }
        public int BabyInfoID { get; set; }
    
        public virtual BabyInfo BabyInfo { get; set; }
    }
}
