//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcementform
    {
        public int ID { get; set; }
        public string Atitle { get; set; }
        public string Acontent { get; set; }
        public System.DateTime Acreatetime { get; set; }
        public bool AIsdelete { get; set; }
        public int AdministratorsID { get; set; }
    
        public virtual AdministratorsSet AdministratorsSet { get; set; }
    }
}
