//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BabyInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BabyInfo()
        {
            this.Album = new HashSet<Album>();
            this.Growthrecord = new HashSet<Growthrecord>();
        }
    
        public int ID { get; set; }
        public string Bname { get; set; }
        public string BLittle { get; set; }
        public string BSex { get; set; }
        public Nullable<System.DateTime> BBirthday { get; set; }
        public string BQRcode { get; set; }
        public string BHeadimg { get; set; }
        public string Bconstellation { get; set; }
        public Nullable<System.DateTime> BBirthtime { get; set; }
        public Nullable<double> Bheight { get; set; }
        public Nullable<double> BWidth { get; set; }
        public Nullable<double> BHeadcircumference { get; set; }
        public System.DateTime Bcreatetime { get; set; }
        public bool BIsdelete { get; set; }
        public int UserInfoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album> Album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Growthrecord> Growthrecord { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
