//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commoditylist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commoditylist()
        {
            this.Brand = new HashSet<Brand>();
            this.Collection = new HashSet<Collection>();
            this.Commoditypicture = new HashSet<Commoditypicture>();
            this.Footprint = new HashSet<Footprint>();
            this.ShoppingCart = new HashSet<ShoppingCart>();
            this.UserFeedback = new HashSet<UserFeedback>();
            this.Orderlist = new HashSet<Orderlist>();
            this.spTypeDetails = new HashSet<spTypeDetails>();
        }
    
        public int ID { get; set; }
        public string Tradename { get; set; }
        public string ProductBrief { get; set; }
        public int Displaylevel { get; set; }
        public Nullable<double> Originalprice { get; set; }
        public double Currentprice { get; set; }
        public int Number { get; set; }
        public Nullable<double> Courierfee { get; set; }
        public Nullable<double> Discount { get; set; }
        public short state { get; set; }
        public System.DateTime Ccreatetime { get; set; }
        public bool CIsdelete { get; set; }
        public int CommodityTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Brand> Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commoditypicture> Commoditypicture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Footprint> Footprint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFeedback> UserFeedback { get; set; }
        public virtual CommodityType CommodityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderlist> Orderlist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spTypeDetails> spTypeDetails { get; set; }
    }
}
