//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commodityconcern
    {
        public int ID { get; set; }
        public System.DateTime Ccreatetime { get; set; }
        public bool CIsdelete { get; set; }
        public int MerchantID { get; set; }
        public int UserInfoID { get; set; }
    
        public virtual Merchant Merchant { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
