//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListenType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListenType()
        {
            this.Listen = new HashSet<Listen>();
        }
    
        public int ID { get; set; }
        public string title { get; set; }
        public System.DateTime Createtime { get; set; }
        public bool Isdelete { get; set; }
        public int AdministratorsID { get; set; }
    
        public virtual AdministratorsSet AdministratorsSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Listen> Listen { get; set; }
    }
}
