//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merchant()
        {
            this.chat = new HashSet<chat>();
            this.Commodityconcern = new HashSet<Commodityconcern>();
            this.MerchantFeedback = new HashSet<MerchantFeedback>();
        }
    
        public int ID { get; set; }
        public string Mname { get; set; }
        public string Mheadimg { get; set; }
        public string Mrealname { get; set; }
        public string MPwd { get; set; }
        public string MSex { get; set; }
        public int MAge { get; set; }
        public string Maddress { get; set; }
        public string Mlevel { get; set; }
        public string Mphone { get; set; }
        public string MIDnum { get; set; }
        public string Mbusiness { get; set; }
        public string MShopphotos { get; set; }
        public string MEmail { get; set; }
        public string Mdescribe { get; set; }
        public System.DateTime Mcreatetime { get; set; }
        public int MIsdelete { get; set; }
        public int AdministratorsID { get; set; }
    
        public virtual AdministratorsSet AdministratorsSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chat> chat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commodityconcern> Commodityconcern { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerchantFeedback> MerchantFeedback { get; set; }
    }
}
