//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baby.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BabyDBEntities : DbContext
    {
        public BabyDBEntities()
            : base("name=BabyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADintegral> ADintegral { get; set; }
        public virtual DbSet<AdministratorsSet> AdministratorsSet { get; set; }
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<Announcementform> Announcementform { get; set; }
        public virtual DbSet<BabyInfo> BabyInfo { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<chat> chat { get; set; }
        public virtual DbSet<Collection> Collection { get; set; }
        public virtual DbSet<Commodityconcern> Commodityconcern { get; set; }
        public virtual DbSet<Commoditylist> Commoditylist { get; set; }
        public virtual DbSet<Commoditypicture> Commoditypicture { get; set; }
        public virtual DbSet<CommodityType> CommodityType { get; set; }
        public virtual DbSet<Evaluation> Evaluation { get; set; }
        public virtual DbSet<Footprint> Footprint { get; set; }
        public virtual DbSet<Growthrecord> Growthrecord { get; set; }
        public virtual DbSet<KnowledgeSet> KnowledgeSet { get; set; }
        public virtual DbSet<knowledgeType> knowledgeType { get; set; }
        public virtual DbSet<Listen> Listen { get; set; }
        public virtual DbSet<ListenType> ListenType { get; set; }
        public virtual DbSet<Merchant> Merchant { get; set; }
        public virtual DbSet<MerchantFeedback> MerchantFeedback { get; set; }
        public virtual DbSet<News_content> News_content { get; set; }
        public virtual DbSet<News_picture> News_picture { get; set; }
        public virtual DbSet<Orderlist> Orderlist { get; set; }
        public virtual DbSet<Problem> Problem { get; set; }
        public virtual DbSet<Sensitivewords> Sensitivewords { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<specificationType> specificationType { get; set; }
        public virtual DbSet<spTypeDetails> spTypeDetails { get; set; }
        public virtual DbSet<UserAddress> UserAddress { get; set; }
        public virtual DbSet<UserFeedback> UserFeedback { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Userintegral> Userintegral { get; set; }
        public virtual DbSet<Order> Order { get; set; }
    }
}
