//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderId { get; set; }
        public double OPriceTotal { get; set; }
        public int Onum { get; set; }
        public System.DateTime Ocreatetime { get; set; }
        public bool OIsdelete { get; set; }
        public int UserInfoID { get; set; }
        public int UserAddressID { get; set; }
    
        public virtual UserAddress UserAddress { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
