//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensitivewords
    {
        public int ID { get; set; }
        public string SProhibit { get; set; }
        public string Sreplace { get; set; }
        public System.DateTime Screatetime { get; set; }
        public bool SIsdelete { get; set; }
    }
}
